[package]
name = "skyrim_anim_parser"
version = "0.1.0"
description = "D merge core"

authors.workspace = true
categories = ["development-tools"]
edition.workspace = true
keywords = ["skyrim"]
license.workspace = true
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }   # Implement (De)Serializer
serde_hkx = { workspace = true }
tracing = { workspace = true, optional = true }
winnow = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
quick_tracing = { workspace = true }
serde_hkx_features = { workspace = true }

[lints]
workspace = true

[features]
default = ["tracing"] # for debug
serde = ["dep:serde"]

tracing = ["dep:tracing"]
