[package]
name = "nemesis_merge"
version = "0.1.0"
description = "D merge core"

authors.workspace = true
categories = ["development-tools"]
edition.workspace = true
keywords = ["skyrim"]
license.workspace = true
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
dashmap = { version = "6.1.0", features = ["rayon"] }
jwalk = { workspace = true }
phf = { workspace = true, features = ["macros"] }
rayon = { workspace = true }
serde_hkx = { workspace = true }
serde_hkx_features = { workspace = true, features = ["extra_fmt"] }
simd-json = { workspace = true, optional = true }
snafu = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, optional = true }
winnow = { workspace = true }

# To type aliases
havok_classes = { workspace = true }
indexmap = { workspace = true }

# workspace members
json_patch = { workspace = true, features = ["rayon"] }
nemesis_xml = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
quick_tracing = { workspace = true }
tokio = { workspace = true, features = [
  "rt",
  "macros",
] } # Need rt & macros for test

[lints]
workspace = true

[features]
default = ["serde"]
# Output patch json, json just before hkx
debug = ["tracing"]
tracing = ["dep:tracing"]

serde = ["dep:simd-json", "json_patch/serde"]
