[package]
name = "nemesis_merge"
version = "0.1.0"
description = "D merge core"

authors.workspace = true
categories = ["development-tools"]
edition.workspace = true
keywords = ["skyrim"]
license.workspace = true
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
dashmap = { version = "6.1.0", features = ["rayon"] }
indexmap = { workspace = true }
jwalk = { workspace = true }
phf = { workspace = true, features = ["macros"] }
rayon = { workspace = true }
serde = { workspace = true, optional = true }
serde_hkx = { workspace = true }
serde_hkx_features = { workspace = true, features = [
  "extra_fmt",
  "serde_default",
] }
simd-json = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, optional = true }
winnow = { workspace = true }

# workspace members
json_patch = { workspace = true, features = ["rayon"] }
nemesis_xml = { workspace = true }
skyrim_anim_parser = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
quick_tracing = { workspace = true }
rmp-serde = { workspace = true }
tokio = { workspace = true, features = [
  "rt",
  "macros",
] } # Need rt & macros for test
tracing-subscriber = { workspace = true }

[lints]
workspace = true

[features]
default = ["debug"]

# Output patch json, json just before hkx
debug = ["serde", "tracing", "dashmap/serde"]

# tracing = ["dep:tracing", "json_patch/tracing", "serde_hkx/tracing"]
tracing = ["dep:tracing", "json_patch/tracing"]

serde = ["dep:serde", "json_patch/serde"]

# Enables TypeScript-compatible serialization for the `Status` enum.
# This feature modifies the `Status` enum to use Serde's externally tagged representation
# with `type` and `message` keys, making it easier to consume in TypeScript/JavaScript frontend.
#
# Example serialized form:
#   { "type": "ReadingTemplatesAndPatches" }
#   { "type": "Error", "message": "Something went wrong" }
#
# Disable this feature if you prefer the default Rust/Serde enum format.
ts_serde = []
