name: Build & Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:

env:
  APP_NAME: d_merge
  BUILD_PROFILE: release-no-lto
  CARGO_TERM_COLOR: always

jobs:
  lint:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup environment
        uses: ./.github/workflows/common_setup.yaml
        with:
          platform: ${{ matrix.platform }}
          build_profile: ${{ env.BUILD_PROFILE }}
          cargo_cache_key_prefix: -debug
          install_front_deps: false

      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint Check
        run: cargo clippy --workspace -- -D warnings

  test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup environment
        uses: ./.github/workflows/common_setup.yaml
        with:
          platform: ${{ matrix.platform }}
          build_profile: ${{ env.BUILD_PROFILE }}
          cargo_cache_key_prefix: -debug
          install_front_deps: false

      - name: Install nextest(Parallel Test Execution CLI)
        uses: taiki-e/install-action@nextest

      - name: Test(Rust)
        run: cargo nextest run --workspace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        if: runner.os == 'Linux'
        with:
          name: d_merge-debug-files
          path: ./dummy/

  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup environment
        uses: ./.github/workflows/common_setup.yaml
        with:
          platform: ${{ matrix.platform }}
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Test(Node.js)
        run: npm test
      - name: Build GUI
        run: npm run build

      - name: Move exe -> ./build
        uses: ./.github/workflows/common_setup_release.yaml
        with:
          app_name: d_merge
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.APP_NAME }}-${{ runner.os }}
          path: |
            ./build/
