name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # <- Setting to allow manual execution by button.

env:
  CARGO_TERM_COLOR: always
  BUILD_PROFILE: release-no-lto
  APP_NAME: egui_d_merge

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.5
        with:
          prefix-key: cargo-egui-${{ env.BUILD_PROFILE }}-${{ matrix.platform }}

      - name: Build (EGUI)
        run: cargo build --release -p egui_d_merge

      # ----------------------------------------------------------------------------------------------------------------
      - name: Compress outputs(Windows)
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          mkdir -p ./build
          Move-Item -Path ./target/${{ env.BUILD_PROFILE }}/${{ env.APP_NAME }}.exe -Destination './build'
          Move-Item -Force -Path ./resource/assets -Destination ./build
      # ----------------------------------------------------------------------------------------------------------------
      - name: Compress outputs(MacOS)
        shell: bash
        if: runner.os == 'macOS'
        run: |
          mkdir -p ./build/assets
          mv ./target/${{ env.BUILD_PROFILE }}/${{ env.APP_NAME }} ./build
          mv ./resource/assets ./build
      # ----------------------------------------------------------------------------------------------------------------
      - name: Compress outputs(Linux)
        shell: bash
        if: runner.os == 'Linux'
        run: |
          mkdir -p ./build/assets
          mv ./target/${{ env.BUILD_PROFILE }}/${{ env.APP_NAME }} ./build
          mv ./resource/assets ./build
      # ----------------------------------------------------------------------------------------------------------------
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ env.APP_NAME }}-${{runner.os}}
          path: |
            ./build/
