name: Common Setup

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build_profile:
        required: false
        type: string
        default: release
      cargo_cache_key_prefix:
        required: false
        type: string
        default: ''
      install_front_deps:
        required: false
        type: boolean
        default: true
jobs:
  setup:
    runs-on: ${{ inputs.platform }}
    outputs:
      platform: ${{ inputs.platform }}
      build_profile: ${{ inputs.build_profile }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Install dependencies (ubuntu only)
        if: inputs.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.8
        with:
          prefix-key: cargo${{ inputs.cargo_cache_key_prefix }}-${{ inputs.build_profile }}-${{ inputs.platform }}

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4.4.0
        if: inputs.install_front_deps
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Next.js cache
        uses: actions/cache@v4.2.3
        if: inputs.install_front_deps
        with:
          path: ${{ github.workspace }}/gui/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('gui/frontend/src/**/*.[jt]s', 'gui/frontend/src/**/*.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
